/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RegisterAsPharmacistRouteImport } from './routes/register-as-pharmacist'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PharmacistSupplyStaffingServicesRouteImport } from './routes/pharmacist-supply-staffing-services'
import { Route as HospitalPharmacyAcquisitionManagementServicesRouteImport } from './routes/hospital-pharmacy-acquisition-management-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulkMedicineProcurementForHospitalsRouteImport } from './routes/bulk-medicine-procurement-for-hospitals'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesPharmacistSupplyStaffingRouteImport } from './routes/services/pharmacist-supply-staffing'
import { Route as ServicesLaboratoryManagementRouteImport } from './routes/services/laboratory-management'
import { Route as ServicesInventoryStockControlRouteImport } from './routes/services/inventory-stock-control'
import { Route as ServicesHospitalPharmacyAcquisitionManagementRouteImport } from './routes/services/hospital-pharmacy-acquisition-management'
import { Route as ServicesConsultingProfitImprovementRouteImport } from './routes/services/consulting-profit-improvement'
import { Route as ServicesComplianceAuditRouteImport } from './routes/services/compliance-audit'
import { Route as ServicesBulkMedicineProcurementRouteImport } from './routes/services/bulk-medicine-procurement'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAsPharmacistRoute = RegisterAsPharmacistRouteImport.update({
  id: '/register-as-pharmacist',
  path: '/register-as-pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistSupplyStaffingServicesRoute =
  PharmacistSupplyStaffingServicesRouteImport.update({
    id: '/pharmacist-supply-staffing-services',
    path: '/pharmacist-supply-staffing-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalPharmacyAcquisitionManagementServicesRoute =
  HospitalPharmacyAcquisitionManagementServicesRouteImport.update({
    id: '/hospital-pharmacy-acquisition-management-services',
    path: '/hospital-pharmacy-acquisition-management-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkMedicineProcurementForHospitalsRoute =
  BulkMedicineProcurementForHospitalsRouteImport.update({
    id: '/bulk-medicine-procurement-for-hospitals',
    path: '/bulk-medicine-procurement-for-hospitals',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPharmacistSupplyStaffingRoute =
  ServicesPharmacistSupplyStaffingRouteImport.update({
    id: '/services/pharmacist-supply-staffing',
    path: '/services/pharmacist-supply-staffing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLaboratoryManagementRoute =
  ServicesLaboratoryManagementRouteImport.update({
    id: '/services/laboratory-management',
    path: '/services/laboratory-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInventoryStockControlRoute =
  ServicesInventoryStockControlRouteImport.update({
    id: '/services/inventory-stock-control',
    path: '/services/inventory-stock-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHospitalPharmacyAcquisitionManagementRoute =
  ServicesHospitalPharmacyAcquisitionManagementRouteImport.update({
    id: '/services/hospital-pharmacy-acquisition-management',
    path: '/services/hospital-pharmacy-acquisition-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesConsultingProfitImprovementRoute =
  ServicesConsultingProfitImprovementRouteImport.update({
    id: '/services/consulting-profit-improvement',
    path: '/services/consulting-profit-improvement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesComplianceAuditRoute = ServicesComplianceAuditRouteImport.update({
  id: '/services/compliance-audit',
  path: '/services/compliance-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBulkMedicineProcurementRoute =
  ServicesBulkMedicineProcurementRouteImport.update({
    id: '/services/bulk-medicine-procurement',
    path: '/services/bulk-medicine-procurement',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bulk-medicine-procurement-for-hospitals': typeof BulkMedicineProcurementForHospitalsRoute
  '/contact': typeof ContactRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
  '/pharmacist-supply-staffing-services': typeof PharmacistSupplyStaffingServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-as-pharmacist': typeof RegisterAsPharmacistRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/bulk-medicine-procurement': typeof ServicesBulkMedicineProcurementRoute
  '/services/compliance-audit': typeof ServicesComplianceAuditRoute
  '/services/consulting-profit-improvement': typeof ServicesConsultingProfitImprovementRoute
  '/services/hospital-pharmacy-acquisition-management': typeof ServicesHospitalPharmacyAcquisitionManagementRoute
  '/services/inventory-stock-control': typeof ServicesInventoryStockControlRoute
  '/services/laboratory-management': typeof ServicesLaboratoryManagementRoute
  '/services/pharmacist-supply-staffing': typeof ServicesPharmacistSupplyStaffingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bulk-medicine-procurement-for-hospitals': typeof BulkMedicineProcurementForHospitalsRoute
  '/contact': typeof ContactRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
  '/pharmacist-supply-staffing-services': typeof PharmacistSupplyStaffingServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-as-pharmacist': typeof RegisterAsPharmacistRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/bulk-medicine-procurement': typeof ServicesBulkMedicineProcurementRoute
  '/services/compliance-audit': typeof ServicesComplianceAuditRoute
  '/services/consulting-profit-improvement': typeof ServicesConsultingProfitImprovementRoute
  '/services/hospital-pharmacy-acquisition-management': typeof ServicesHospitalPharmacyAcquisitionManagementRoute
  '/services/inventory-stock-control': typeof ServicesInventoryStockControlRoute
  '/services/laboratory-management': typeof ServicesLaboratoryManagementRoute
  '/services/pharmacist-supply-staffing': typeof ServicesPharmacistSupplyStaffingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bulk-medicine-procurement-for-hospitals': typeof BulkMedicineProcurementForHospitalsRoute
  '/contact': typeof ContactRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
  '/pharmacist-supply-staffing-services': typeof PharmacistSupplyStaffingServicesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register-as-pharmacist': typeof RegisterAsPharmacistRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/bulk-medicine-procurement': typeof ServicesBulkMedicineProcurementRoute
  '/services/compliance-audit': typeof ServicesComplianceAuditRoute
  '/services/consulting-profit-improvement': typeof ServicesConsultingProfitImprovementRoute
  '/services/hospital-pharmacy-acquisition-management': typeof ServicesHospitalPharmacyAcquisitionManagementRoute
  '/services/inventory-stock-control': typeof ServicesInventoryStockControlRoute
  '/services/laboratory-management': typeof ServicesLaboratoryManagementRoute
  '/services/pharmacist-supply-staffing': typeof ServicesPharmacistSupplyStaffingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/bulk-medicine-procurement-for-hospitals'
    | '/contact'
    | '/hospital-pharmacy-acquisition-management-services'
    | '/pharmacist-supply-staffing-services'
    | '/privacy-policy'
    | '/register-as-pharmacist'
    | '/terms-of-service'
    | '/services/bulk-medicine-procurement'
    | '/services/compliance-audit'
    | '/services/consulting-profit-improvement'
    | '/services/hospital-pharmacy-acquisition-management'
    | '/services/inventory-stock-control'
    | '/services/laboratory-management'
    | '/services/pharmacist-supply-staffing'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/bulk-medicine-procurement-for-hospitals'
    | '/contact'
    | '/hospital-pharmacy-acquisition-management-services'
    | '/pharmacist-supply-staffing-services'
    | '/privacy-policy'
    | '/register-as-pharmacist'
    | '/terms-of-service'
    | '/services/bulk-medicine-procurement'
    | '/services/compliance-audit'
    | '/services/consulting-profit-improvement'
    | '/services/hospital-pharmacy-acquisition-management'
    | '/services/inventory-stock-control'
    | '/services/laboratory-management'
    | '/services/pharmacist-supply-staffing'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/bulk-medicine-procurement-for-hospitals'
    | '/contact'
    | '/hospital-pharmacy-acquisition-management-services'
    | '/pharmacist-supply-staffing-services'
    | '/privacy-policy'
    | '/register-as-pharmacist'
    | '/terms-of-service'
    | '/services/bulk-medicine-procurement'
    | '/services/compliance-audit'
    | '/services/consulting-profit-improvement'
    | '/services/hospital-pharmacy-acquisition-management'
    | '/services/inventory-stock-control'
    | '/services/laboratory-management'
    | '/services/pharmacist-supply-staffing'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BulkMedicineProcurementForHospitalsRoute: typeof BulkMedicineProcurementForHospitalsRoute
  ContactRoute: typeof ContactRoute
  HospitalPharmacyAcquisitionManagementServicesRoute: typeof HospitalPharmacyAcquisitionManagementServicesRoute
  PharmacistSupplyStaffingServicesRoute: typeof PharmacistSupplyStaffingServicesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterAsPharmacistRoute: typeof RegisterAsPharmacistRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ServicesBulkMedicineProcurementRoute: typeof ServicesBulkMedicineProcurementRoute
  ServicesComplianceAuditRoute: typeof ServicesComplianceAuditRoute
  ServicesConsultingProfitImprovementRoute: typeof ServicesConsultingProfitImprovementRoute
  ServicesHospitalPharmacyAcquisitionManagementRoute: typeof ServicesHospitalPharmacyAcquisitionManagementRoute
  ServicesInventoryStockControlRoute: typeof ServicesInventoryStockControlRoute
  ServicesLaboratoryManagementRoute: typeof ServicesLaboratoryManagementRoute
  ServicesPharmacistSupplyStaffingRoute: typeof ServicesPharmacistSupplyStaffingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-as-pharmacist': {
      id: '/register-as-pharmacist'
      path: '/register-as-pharmacist'
      fullPath: '/register-as-pharmacist'
      preLoaderRoute: typeof RegisterAsPharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist-supply-staffing-services': {
      id: '/pharmacist-supply-staffing-services'
      path: '/pharmacist-supply-staffing-services'
      fullPath: '/pharmacist-supply-staffing-services'
      preLoaderRoute: typeof PharmacistSupplyStaffingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-pharmacy-acquisition-management-services': {
      id: '/hospital-pharmacy-acquisition-management-services'
      path: '/hospital-pharmacy-acquisition-management-services'
      fullPath: '/hospital-pharmacy-acquisition-management-services'
      preLoaderRoute: typeof HospitalPharmacyAcquisitionManagementServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-medicine-procurement-for-hospitals': {
      id: '/bulk-medicine-procurement-for-hospitals'
      path: '/bulk-medicine-procurement-for-hospitals'
      fullPath: '/bulk-medicine-procurement-for-hospitals'
      preLoaderRoute: typeof BulkMedicineProcurementForHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pharmacist-supply-staffing': {
      id: '/services/pharmacist-supply-staffing'
      path: '/services/pharmacist-supply-staffing'
      fullPath: '/services/pharmacist-supply-staffing'
      preLoaderRoute: typeof ServicesPharmacistSupplyStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/laboratory-management': {
      id: '/services/laboratory-management'
      path: '/services/laboratory-management'
      fullPath: '/services/laboratory-management'
      preLoaderRoute: typeof ServicesLaboratoryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/inventory-stock-control': {
      id: '/services/inventory-stock-control'
      path: '/services/inventory-stock-control'
      fullPath: '/services/inventory-stock-control'
      preLoaderRoute: typeof ServicesInventoryStockControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hospital-pharmacy-acquisition-management': {
      id: '/services/hospital-pharmacy-acquisition-management'
      path: '/services/hospital-pharmacy-acquisition-management'
      fullPath: '/services/hospital-pharmacy-acquisition-management'
      preLoaderRoute: typeof ServicesHospitalPharmacyAcquisitionManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consulting-profit-improvement': {
      id: '/services/consulting-profit-improvement'
      path: '/services/consulting-profit-improvement'
      fullPath: '/services/consulting-profit-improvement'
      preLoaderRoute: typeof ServicesConsultingProfitImprovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/compliance-audit': {
      id: '/services/compliance-audit'
      path: '/services/compliance-audit'
      fullPath: '/services/compliance-audit'
      preLoaderRoute: typeof ServicesComplianceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bulk-medicine-procurement': {
      id: '/services/bulk-medicine-procurement'
      path: '/services/bulk-medicine-procurement'
      fullPath: '/services/bulk-medicine-procurement'
      preLoaderRoute: typeof ServicesBulkMedicineProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BulkMedicineProcurementForHospitalsRoute:
    BulkMedicineProcurementForHospitalsRoute,
  ContactRoute: ContactRoute,
  HospitalPharmacyAcquisitionManagementServicesRoute:
    HospitalPharmacyAcquisitionManagementServicesRoute,
  PharmacistSupplyStaffingServicesRoute: PharmacistSupplyStaffingServicesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterAsPharmacistRoute: RegisterAsPharmacistRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ServicesBulkMedicineProcurementRoute: ServicesBulkMedicineProcurementRoute,
  ServicesComplianceAuditRoute: ServicesComplianceAuditRoute,
  ServicesConsultingProfitImprovementRoute:
    ServicesConsultingProfitImprovementRoute,
  ServicesHospitalPharmacyAcquisitionManagementRoute:
    ServicesHospitalPharmacyAcquisitionManagementRoute,
  ServicesInventoryStockControlRoute: ServicesInventoryStockControlRoute,
  ServicesLaboratoryManagementRoute: ServicesLaboratoryManagementRoute,
  ServicesPharmacistSupplyStaffingRoute: ServicesPharmacistSupplyStaffingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
