/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HospitalPharmacyAcquisitionManagementServicesRouteImport } from './routes/hospital-pharmacy-acquisition-management-services'
import { Route as IndexRouteImport } from './routes/index'

const HospitalPharmacyAcquisitionManagementServicesRoute =
  HospitalPharmacyAcquisitionManagementServicesRouteImport.update({
    id: '/hospital-pharmacy-acquisition-management-services',
    path: '/hospital-pharmacy-acquisition-management-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hospital-pharmacy-acquisition-management-services': typeof HospitalPharmacyAcquisitionManagementServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hospital-pharmacy-acquisition-management-services'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hospital-pharmacy-acquisition-management-services'
  id: '__root__' | '/' | '/hospital-pharmacy-acquisition-management-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HospitalPharmacyAcquisitionManagementServicesRoute: typeof HospitalPharmacyAcquisitionManagementServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hospital-pharmacy-acquisition-management-services': {
      id: '/hospital-pharmacy-acquisition-management-services'
      path: '/hospital-pharmacy-acquisition-management-services'
      fullPath: '/hospital-pharmacy-acquisition-management-services'
      preLoaderRoute: typeof HospitalPharmacyAcquisitionManagementServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HospitalPharmacyAcquisitionManagementServicesRoute:
    HospitalPharmacyAcquisitionManagementServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
